// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tivcdfqevfcajxbpzfwk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRpdmNkZnFldmZjYWp4YnB6ZndrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQxNzQwMDYsImV4cCI6MjA2OTc1MDAwNn0.PtehXhRapXBC7kh1LRiw9SE9WrG251CthCdtZ6T8Lvw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});